# Generated by Django 4.1.7 on 2023-03-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_remove_file_uploaded_at_alter_file_file_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='data2',
        ),
    ]
